### ISSUE TITLE
Sites erroring in 2.process-cells

### ISSUE THREAD

**Issue by ErinWeisbart** [broadinstitute/pooled-cell-painting-profiling-recipe#25]
Currently 10 sites error in 2.process-cells with "151B2-B1-87 data not found" message.
We need to dig a bit to figure out why those particular sites are erroring. If possible, a more descriptive error message would be nice to implement to assist in tracking down why those sites error.
151B2-B1-83
151B2-B1-85
151B2-B1-87
151B2-B1-88
151B2-B1-89
151B2-B2-11
151B2-B2-16
151B2-B2-19
151B2-B2-22
151B2-B2-26

**Comment by gwaygenomics** [comment]
@ErinWeisbart - can I assign this issue to you? We'll need to get this sorted out before version 0.1 release.

If you are able to take this on, is there anything I can do to help?

**Comment by ErinWeisbart** [comment]
I re-downloaded the files and didn't get any errors this time, so the files must have been corrupted in download the first time.
So I think we can just close this.

**Comment by gwaygenomics** [comment]
the best kind of bug fix!

Is it worth opening a new issue to check for corrupted files? I wonder if this could be part of the "more descriptive error message". f"Potentially corrupted files found in site: {site} - data failed to process " 👈 maybe something like this?

**Comment by ErinWeisbart** [comment]
I don't have a great understanding of the failure space, so I'm not sure what my answer is.
Is a corrupted file the only thing (or almost the only thing) that would cause an error like that? If so then just adding in that error message sounds great.
If many causes are possible/likely, then can we add in some way to check that the file is indeed corrupted and then give your message?
Or we could start a page on the wiki for potential errors/causes/fixes?

**Comment by gwaygenomics** [comment]
Good point - we definitely don't know the complete failure space. It does seem likely that more than just a corrupted file will throw the error...

I agree that we should track errors somewhere (github issues has worked well so far) and solve them as we get to them.

**Comment by gwaygenomics** [comment]
I'm going to move this issue off the the version 0.1 milestone - we can continue with it open, but I suspect that we'll close it in favor of more specific issues that we'll inevitably come across in future experiments

**Comment by ErinWeisbart** [comment]
Because we were unable to replicate this specific error on a second pass, we don't know what caused it the first time through, and we haven't found the same/similar issue in the last year with other datasets, I am closing this issue.
