### ISSUE TITLE
process_cells config mismatch

### ISSUE THREAD

**Issue by ErinWeisbart** [broadinstitute/pooled-cell-painting-profiling-recipe#26]
In the config for process_cells we have `prefilter-features` as a Bool but in 2.process-cells.py is requires running 0.preprocess-sites.py first so that you have a prefilter file as input.

@gwaygenomics What is the goal of this config Bool? 
Do we want to update 2.process-cells.py to allow for not using a prefilter file? Or do we want to remove the input from the config?

**Comment by gwaygenomics** [comment]
yeah, i agree this is weird... lets remove prefilter-features from the config
