### ISSUE TITLE
4.image-and-segmentation-qc.py should produce figures on a per-plate basis

### ISSUE THREAD

**Issue by ErinWeisbart** [broadinstitute/pooled-cell-painting-profiling-recipe#74]
@gwaygenomics I'm happy to address this. 

I remember you saying you were going to do some re-factoring to address handling our current experiment structure where a single batch can contain many plates. Will that affect the structure of inputs for this step? (i.e. image_metadata.tsv and cell_count.tsv)? (They already have Metadata_Plate columns that include both plates in the current batch we're working on, so I would assume not...?)

**Comment by gwaygenomics** [comment]
Awesome! I already performed the refactoring (see #71 ) this didn't impact the image-and-segmentation file much ([see here](https://github.com/broadinstitute/pooled-cell-painting-profiling-recipe/blob/7b7f8d6609f93573e3ad62e1add1c6f97cf66bfb/0.preprocess-sites/4.image-and-segmentation-qc.py)).

They key thing in #71 is that the user is now able to define data splits in the config (see below) - and decide to use these splits in QC and profiling _separately_. This is done through the function [`data_split_utils.get_split_aware_site_info()`](https://github.com/broadinstitute/pooled-cell-painting-profiling-template/blob/b51400588563e61a90cccd20e2a7b2a2f7c4bea2/config/utils/data_split_utils.py) which we define the template repo. 

![image](https://user-images.githubusercontent.com/7340421/121250537-d5481f80-c873-11eb-8f4e-ec85a3f53a76.png)

You may decide to use this function, or not, in your modification. It may be more complicated than need be, especially if a user _always_ wants to track these QC metrics on a per plate basis

**Comment by ErinWeisbart** [comment]
Great! 

I think that, given the primary function of this module is to provide an easy-to-peruse visual overview, and that any concerns raised by these overviews would need to be addressed in more detail elsewhere, there's no need to build the split into this step as one would always want to see metrics for the whole plate (and even if one didn't it can't hurt to have the extra information). 

(I guess I can imagine a scenario where one part of a plate performs so dramatically differently that setting scales across the whole plate for visualization makes it difficult to see what's going on in one split or another... but I don't see that really happening in practice... )

**Comment by gwaygenomics** [comment]
sounds good, i'm 100% for doing the simpler thing
